<?php

/**
 * @file
 * Control where users are directed to, once they login
 */

// Page constants
define('LOGIN_DESTINATION_REDIRECT_NOTLISTED', 0);
define('LOGIN_DESTINATION_REDIRECT_LISTED', 1);
define('LOGIN_DESTINATION_REDIRECT_PHP', 2);

// Destination constants
define('LOGIN_DESTINATION_STATIC', 0);
define('LOGIN_DESTINATION_SNIPPET', 1);

/**
 * Implement hook_help().
 */
function login_destination_help($path, $arg) {
  switch ($path) {
    case 'admin/help#login_destination':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Login Destination module allows you to customize the destination that the user is redirected to after logging in, registering to the site, using a one-time login link or logging out. The destination can be an internal page or an external URL. You may specify certain conditions like pages or user roles and make the destination depend upon them. You may also use a PHP snippets to provide custom conditions and destinations. Note that PHP Filter module has to be enabled and you have to be granted the "Use PHP for settings" permissions to be able to enter PHP code.') . '</p>';
      return $output;
    case 'admin/config/people/login-destination':
      return '<p>' . t('Login destination rules are evaluated each time a user logs in, registers to the site, uses a one-time login link or logs out. Each rule consists of the destination, path conditions and user roles conditions. First matching rule gets executed.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 * @return array
 */
function login_destination_menu(){
  $items = array();

  $items['admin/config/people/login-destination'] = array(
    'title' => 'Login destinations',
    'description' => 'Customize the destination that the user is redirected to after login.',
    'route_name' => 'login_destination.list',
    'weight' => 10,
  );
  $items['admin/config/people/login-destination/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/people/login-destination/settings'] = array(
    'title' => 'Settings',
    'description' => 'Change Login Destination settings.',
    'route_name' => 'login_destination.settings',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  return $items;
}

/**
 * A helper function to provide role options
 */
function _login_destination_role_options() {
  // user role selection, without anonymous and authentificated user roles.
  $roles = array_keys(user_roles(TRUE));
  $role_options = array_combine($roles, $roles);
  unset($role_options[DRUPAL_AUTHENTICATED_RID]);

  return $role_options;
}

/**
 * Load a login destination.
 */
function login_destination_load($id) {
  return entity_load('login_destination', $id);
}